### ISSUE TITLE
How to handle CORS error?

### ISSUE THREAD

**Issue by weisisheng** [bradtraversy/react-admin-example#1]
Followed video meticulously and then checking code here, I needed to add the dependency "content-range".  

Still I get an error and can't get original posts from db.json

Access to fetch at 'http://localhost:3000/posts?filter=%7B%7D&range=%5B0%2C9%5D&sort=%5B%22id%22%2C%22ASC%22%5D' from origin 'http://0.0.0.0:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:5000' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Tried additional settings but no luck and I am a noob at CORS.

    res.header("Access-Control-Allow-Origin",  "*");
    res.header("Access-Control-Allow-Credentials", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, authorization");
    res.header("Access-Control-Allow-Methods", "GET, POST, OPTIONS, PUT, DELETE");  

Appreciate any tips, tricks...Thanks.

**Comment by weisisheng** [comment]
Not a perfect fix but I changed the 'localhost' reference in App.js to '0.0.0.0' and data table renders

**Comment by aindriu80** [comment]
I had the CORS error as well but I think you just need `  "proxy": "http://localhost:5000",` in client package.json , it's definitely a bit buggy though
